### ISSUE TITLE
Multiple axes in a single direction do not work if both axis are using same type of graph.

### ISSUE THREAD

**Issue by boltex** [ag-grid/ag-charts#1]
**Multiple axes in a single direction do not work if both axis are using same type of graph.**

To reproduce, use the https://www.ag-grid.com/angular-charts/axes/#example-multiple-axes official example

change the second series type from 'line' to 'column' : the right axis grid and labels disappear, and the second axis columns are simply shown in relation to the left axis.

1- before with the second series as 'line' it has it's own scale axis on the right

![screenshot 77](https://user-images.githubusercontent.com/847716/157738615-02a96002-f98f-4a9a-940a-f1cf30bb0dd1.png)

 2- change 'line' to 'column' 

![screenshot 75](https://user-images.githubusercontent.com/847716/157735225-04e4f41e-f869-4636-b9ca-cddcb7ba9cb9.png)

3- Graph no longer has grid lines nor labels for right side axis. Only label remains and its associated yKey data is scaled on the left side axis.

![screenshot 76](https://user-images.githubusercontent.com/847716/157735971-fa34a1f9-b26f-4c13-8162-a2975e7d7481.png)

**Comment by kiril-matev** [comment]
Hello @boltex,

Thanks for getting in touch.

The functionality you described wasn't part of the requirements when we built this feature - the column series doesn't currently support secondary Y-axes. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-6560 [Chart] Add support for secondary axis for grouped column series**

We have no timeline for the implementation of this. In the meantime, please use a combination chart - columns and line, which can help you support a secondary Y-axis as shown below:
https://www.ag-grid.com/angular-charts/axes/#example-multiple-axes

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by kiril-matev** [comment]
Hi @boltex,

**This is a legacy repository.**

We will now close this issue and archive this repository soon to avoid any further confusion. **If you want to open any new issues, please report them under the main repository to ensure they are processed promptly and seen by the entire AG Grid community.**
