### ISSUE TITLE
Better a11y support

### ISSUE THREAD

**Issue by nayfin** [ag-grid/ag-charts#1074]
**I'm submitting a ...** (check one with "x")

```
[] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Charts team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, our staff will label your issue as managed-by-the-community. This means that AG Grid staff will not be actively looking into it and it will be closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are

-   Inspect chart element of any example (like this one https://charts.ag-grid.com/angular/bubble-series/#labels) check for "role" or "aria-label" attributes. They won't be there

If reporting a bug make sure to state:

-   Current behaviour.
-   Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

Visualizations are created in canvas without any a11y attributes to provide information for screen readers.

**Expected behavior**

Minimum: 
- role="img" added to canvas element
- aria-label="Value of chart's label property used here"

Preferred:
- aria-label="String describing graph constructed from it's values or configurable by consuming developer"

**Please tell us about your environment:**

n/a

-   **AG Charts version:** X.X.X
all

-   **Browser:**
n/a

-   **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-DavidG** [comment]
Hello @nayfin 

Thank you for bringing this up with us. 

The functionality you described wasn't part of the requirements when we built this feature. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
AG-5929 - [Accessibility] Add keyboard navigation and screen reader announcements to charts

You can follow the status of feature requests, bugs and releases using our pipeline:
https://charts.ag-grid.com/pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. Once a new AG Charts version is released, look for the item reference above (AG-5929) on the changelog page to see if it's resolved in that version:
https://charts.ag-grid.com/changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by AG-DavidG** [comment]
Hi @nayfin 

I just wanted to bring to your attention that we have added accessibility to AG Charts with version 9.3 that has just been released.
 
You can read more about this at https://charts.ag-grid.com/react/accessibility/.
 
I hope that this allows you to integrate AG Charts in your offerings. 
  
Thanks

David
