### ISSUE TITLE
Screen not redrawing?

### ISSUE THREAD

**Issue by kicomoco** [ag-grid/ag-charts#1386]
I'm submitting a support request (community)

I'm using the javascript library, and when I call update() nothing changes on screen....however if I click on an item in the legend to remove it off the chart the data then updates to what I called in the update(). It appears that the chart isn't being redrawn when I call the update() only when I force it by interacting with the chart.

What am I missing?

I'm using Chrome 123.0.6312.106 (Official Build) (64-bit) to view, its running on a webserver being accessed through HTTP.

**Comment by kicomoco** [comment]
Using the JS library on cdn.jsdelivr.net (https://cdn.jsdelivr.net/npm/ag-charts-community/dist/umd/ag-charts-community.js)

**Comment by AG-DavidG** [comment]
Hello @kicomoco !

Thank you for reporting this behavior - much appreciated!

We're keen to look into this but we need to be able to reproduce the issue you've described.

Please provide the following (as per our bug template in Github):
1. A live example (plunker, stackblitz, etc) or link to a repo showing the issue
2. A list of steps to follow to reproduce the issue
3. Descriptions of current behavior and expected behavior

We're looking forward to your response to we can investigate this further.

Thank you!

**Comment by kicomoco** [comment]
Hi David, thanks for getting back to me and apologies for the delay!

I have created a page on a spare domain so you can see the issue live:

https://kicomoco.com/aggraph/test.html

The page loads, the chart is created....and when you click the button it changes the data and calls update(), but the chart doesn't re-render. If you then click on the legend to turn a series off the chart then reflects the updated data. I have also put chartOptions in the console when you click the button so you can see the updated settings.

Current behaviour:
update() is called and the chart doesn't redraw with the updated data until it is interacted with by turning on/off a series.

Expected behaviour:
when update() is called the chart redraws to show the updated data without further interaction.

I hope this helps

Thanks

Richard

**Comment by AG-DavidG** [comment]
Hello @kicomoco 

Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a bug.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-11336 [Charts] Updating a value within a data item does not update chart
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
In the meanwhile, you can force the chart to update by replacing the entire array item instead of just updating the value inside it.
 
You can get an update on the status of this item on the product pipeline page:
https://charts.ag-grid.com/pipeline/
 
Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. Once a new AG Charts version is released, look for the item reference above (AG-11336) on the changelog page to see if it's resolved in that version:
https://charts.ag-grid.com/changelog/
 
Thanks again for bringing this up with us - we appreciate your time!
 
David‍

**Comment by kicomoco** [comment]
Hi David,

Thanks for the update, excellent news that you have been able to reproduce! and thanks for the tip on the workaround, I have this implemented and working.

Thanks

Richard

**Comment by AG-DavidG** [comment]
Hi Richard @kicomoco 

Quick update on this bug. 

We will not be fixing it as that will have an impact on performance. 
We expect immutable data for `data` elements. This is because it allows us to efficiently perform per-element change detection.  Therefore, if `data`
elements are mutated in-place, we cannot guarantee to detect the changes.

As mentioned,  you can force the chart to update by replacing the entire array item instead of just updating the value inside it. It sounds like this is working for you which is good news.

Thanks

David
