### ISSUE TITLE
Chart with autoSize takes parent height regardless of other content

### ISSUE THREAD

**Issue by Caminyx** [ag-grid/ag-charts#1426]
Hello,

**I'm submitting a ...**

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

A chart with autoSize is placed inside a container with fixed or relative height (I tried both).
The chart takes the height of the container even if there is content before it. As a result, the chart overflows the container if any block is placed before it and superpose any block placed after it.
The bug occurs with basic options (only data and series) with at least these chart types : Line, Bar, Pie, Column, Radar, Mixed, Double Scale

**Expected behavior**

The chart should stay within the bounds of the container by taking the remaining space, and not take the parent height.

**Please tell us about your environment:**

-   **AG Charts version:** X.X.X
AG Charts Entreprise 9.2.0
AG Charts Community 9.2.0
AG Charts Vue3 9.2.0

-   **Browser:**
Brave 1.63.162 (chromium 122.0.6261.69)

-   **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Vue 3.2
Typescript 4.8

**Comment by AG-DavidG** [comment]
Hi @Caminyx 

We're keen to look into this but we need to be able to reproduce the issue you've described.

Please provide the following (as per our bug template in Github):
1. A live example (plunker, stackblitz, etc) or link to a repo showing the issue
2. A list of steps to follow to reproduce the issue
3. Descriptions of current behavior and expected behavior

We're looking forward to your response to we can investigate this further.

Thank you!

**Comment by Caminyx** [comment]
Hi @AG-DavidG 
I reproduced the bug on [this plunker](https://plnkr.co/edit/CTeriRaNLqDZCH5g)
Thank you for your help !

**Comment by AG-DavidG** [comment]
Hi @Caminyx 

Thank you for the reproduction. 

What you are seeing is the expected behaviour as documented. Our documentation (https://charts.ag-grid.com/options/#reference-AgChartOptions-autoSize) states:

> By default, the chart will resize automatically to fill the container element 

We recommend that the chart is the only item within its container, or that you provide a fixed size for the chart within the chart options.

However, I have added your use case to ticket number **AG-10200 - [Charts] Improve chart autosize mechanism** in our backlog, for us to consider when we work on this area in future versions.

Thanks

David
