### ISSUE TITLE
Ag-Charts in Vue 3: Broken and Lacking Support

### ISSUE THREAD

**Issue by lucaspmarra** [ag-grid/ag-charts#1587]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- [CodeSandbox](https://codesandbox.io/p/devbox/vue-ag-grid-forked-dmwn7q?file=%2Fsrc%2FApp.vue%3A151%2C9)
- A description:

Ag-Charts in Vue 3 seems to be broken. When will this be fixed? Vue 3 was released in 2022, and it's already 2024, yet there's still no official support for it. We're stuck with Integrated Charts, which lack configuration and customization options.

When I tried using Ag-Charts in Vue 3 (by simply copying the code from the documentation), it didn't work. Here's an example:

```javascript
✘ [ERROR] Could not resolve "vue-class-component"

    node_modules/.pnpm/ag-charts-vue3@9.3.1_ag-charts-community@9.3.1_vue@3.4.15/node_modules/ag-charts-vue3/lib/AgChartsVue.js:9:29:
      9 │ import { Options, Vue } from 'vue-class-component';
        ╵                              ~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "vue-class-component" as external to exclude it from the
  bundle, which will remove this error and leave the unresolved path in the
  bundle.

12:01:55 PM [vite] Pre-transform error: @vnode-* hooks in templates are no longer supported. Use the vue: prefix instead. For example, @vnode-mounted should be changed to @vue:mounted. @vnode-* hooks support has been removed in 3.4.
/workspaces/sandbox/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1651
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
node_modules/.pnpm/ag-charts-vue3@9.3.1_ag-charts-community@9.3.1_vue@3.4.15/node_modules/ag-charts-vue3/lib/AgChartsVue.js:9:29: ERROR: Could not resolve "vue-class-component"
    at failureErrorWithLog (/workspaces/sandbox/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1651:15)
    at /workspaces/sandbox/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1059:25
    at /workspaces/sandbox/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v20.9.0
```
![image](https://github.com/ag-grid/ag-grid/assets/30451874/096cf042-221e-4a4a-8e7a-d26ed033554f)

This code works in the documentation, but not in my actual project. 

* **AG Grid versions:**
 "ag-charts-community": "9.3.1",
 "ag-charts-vue3": "9.3.1",
 "ag-grid-vue3": "31.3.1",
 "vue": "^3.4.15",
"vue-class-component": "^8.0.0-beta.3"

**Comment by AG-DavidG** [comment]
Hello 

Thank you for reporting this - much appreciated!

This should work if you use Vue version 3.3.13 or below.

Vue made a breaking change and we need to update our wrapper to account for this. 

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-11623 - [Charts] Update deprecated vue-class-component in vue wrapper

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://charts.ag-grid.com/pipeline/

The best way to track this is to sign up for AG Charts new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/15387001154205-How-do-I-Sign-Up-For-AG-Charts-Release-Notifications). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://charts.ag-grid.com/changelog/).

Thanks again for bringing this up with us.

Kind regards,

David

**Comment by lucaspmarra** [comment]
Im unable to find the backlog number:
![image](https://github.com/ag-grid/ag-charts/assets/30451874/b7c6da0b-1046-4ed4-80c0-3a4c44cdde87)

![image](https://github.com/ag-grid/ag-charts/assets/30451874/1afea53a-8b5c-4cdb-bbc9-1e0ab4b960c0)

**Comment by AG-DavidG** [comment]
Hi @lucaspmarra 

It should be there now. 

Thanks

David

**Comment by lucaspmarra** [comment]
Thanks, @AG-DavidG!
It's showing now.
