### ISSUE TITLE
Is it possible to load data asynchronously with AgCharts Enterprise without using the timeline as a scaling option?

### ISSUE THREAD

**Issue by codecodecookie** [ag-grid/ag-charts#1618]
I was using the enterprise version of AgCharts and noticed that it had a feature for loading data asynchronously, but the getdata interface's datatypes windowStart and windowEnd could only be datatypes. This was not what I expected. I needed a scaled datatype of type number. How can I implement my function so that I can select the appropriate granularity value according to the difference between the two when I scale and request the corresponding detailed data, thanks in advance.

**Comment by AG-DavidG** [comment]
Hello 

Thank you for the suggestion.

Currently there's no way to implement this behavior with AG Charts. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

You can track it with this reference:
**AG-11729 - [Charts] Allow using dataSource callback for numeric axes**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://charts.ag-grid.com/pipeline/

If you are using a feature of AG Charts Enterprise with a valid license, you can use our support system to register your interest in this feature.

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Charts. 

The best way to get an update on this item is to sign up for AG Charts new release notifications. Once a new AG Charts version is released, look for the item reference above on the changelog page to see if it's resolved in that version:
https://charts.ag-grid.com/changelog/

Thanks again for bringing this up with us.

Kind regards,
