### ISSUE TITLE
Changing visible state of a series via other button

### ISSUE THREAD

**Issue by yaowen-kok-harmonic** [ag-grid/ag-charts#1694]
**I'm submitting a ...** (check one with "x")

```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

Link down below is the plunker:

https://plnkr.co/edit/HLWrCFtNdI8CttdN?open=index.jsx&preview

1. When legend item is set to not visible, updating the options visibility does not change Series's visibility. For example, in the plunker provided above, the toggle buttons toggles the visibility of the "cakeSales" series. However if the visibility is already set off through the legend item, the toggle button stops working entirely and setting the visibility of the series no longer works.

2. If the visibility is set off through the legend item, the series bar resizes. If the visibility is set off through the button/updated option, the series bar does not not resize.

**Expected behavior**

1. The visibility should turn on and off regardless of the legend item's visibility state. I tested the line chart with something similar, the line chart is working fine, just not the bar chart.

2. clicking the legend item vs clicking the toggle button should have the same outcome.

**Comment by AG-DavidG** [comment]
Hello @3322728 

Thank you for reporting this - much appreciated!

There are two points here.

1
The `visible` option is not directly related to the legend toggling of the series. When the legend toggles the series on or off, it does so internally and does not change the `visible` option within the chart options. This is why mixing the two methods does not work.
You can disable the built-in legend toggling via `legend.item.toggleSeriesVisible: false` and add add your own listeners to the legend click events to use the series `visible` options exclusively. 
See https://charts.ag-grid.com/javascript/events/#legend-events---legenditemclick-and-legenditemdoubleclick for more details about this.

2
When updating the `visible` option at runtime, the chart is not moving the other bars appropriately. This means that when removing a series, there are gaps remaining. This also means that when enabling an initially hidden series, no gap is made for it and it does not appear.

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-11800 - [Charts] Bar series do not move position when series has `visible` toggled dynamically at runtime - REGRESSION

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://charts.ag-grid.com/pipeline/

The best way to track this is to sign up for AG Charts new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/15387001154205-How-do-I-Sign-Up-For-AG-Charts-Release-Notifications). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://charts.ag-grid.com/changelog/).

Thanks again for bringing this up with us.

Kind regards,

David
