### ISSUE TITLE
label formatter for treemap

### ISSUE THREAD

**Issue by kingofday** [ag-grid/ag-charts#18]
is there a way to format labels of treemap in each tile, currently it puts percent value based on size and i don't want it, and want to show something else?

**Comment by kiril-matev** [comment]
Hello!

Thank you for bringing this up with us. 

**You opened this issue in a legacy repository instead of the main one, which is why we've not responded to it earlier.**

We have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
AG-5220 [Chart] Add a tile formatter to treemap series

We will deliver this feature in our next release.

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

**We will now close this issue and archive this repository soon to avoid any further confusion. If you want to open any new issues, please report them under the main repository to ensure they are processed promptly and seen by the entire AG Grid community:
https://github.com/ag-grid/ag-grid/issues**

Thanks again for bringing this up with us - we appreciate your time!
