### ISSUE TITLE
MarkerShape is not rendered with ItemStyler in the example (also appears in React version)

### ISSUE THREAD

**Issue by tykim9999** [ag-grid/ag-charts#2267]
**I'm submitting a ...** (check one with "x")

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Charts team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, our staff will label your issue as managed-by-the-community. This means that AG Grid staff will not be actively looking into it and it will be closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are

-  `MarkerShape` is not rendered with ItemStyler in the example (also appears in React version)
-  I added a shape prop to ItemStyler, but it still renders as ‘circle’ by default.
- https://plnkr.co/edit/G1uZ3lLrtlE1BQk5?preview
![image](https://github.com/user-attachments/assets/7656e162-b004-4a8a-bbef-711d18a8aeae)

If you decide to send us a Plunker, from any example in our website use the Plunker button in there to fork your own code by following the steps below:

-   Select the framework that is appropriate to you from the drop-down
-   Open it in Plunker. (Use the button Plunker in our example)
-   Add your changes so that the behaviour is reproduced
-   Save and Freeze the Plunker (On the top left corner)
-   Send us the link to the Plunker (You can copy the URL from the browser)

If reporting a bug make sure to state:

-   Current behaviour.
-   Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

I added a shape prop to ItemStyler, but it still renders as ‘circle’ by default.

**Expected behavior**

The shape prop should render the specified shape instead of defaulting to ‘circle’. 

**Please tell us about your environment:**

-   **AG Charts version:** "ag-charts-react": "^10.1.0-beta.20240807.1446" and "10.0.2"

-   **Browser:**

Safari, Chrome
-   **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AG-DavidG** [comment]
Hello @tykim9999  

Thank you for the question.

Currently there's no way to implement this behavior with AG Charts. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

You can track it with this reference:
AG-11980 - [Charts] Allow itemStylers to change `shape` on all series

You can follow the status of feature requests, bugs and releases using our pipeline:
https://charts.ag-grid.com/pipeline/

Now that this requirement is recorded in our backlog, we will close the GitHub issue because we will not update it when this feature is added in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. Once a new AG Charts version is released, look for the item reference above (AG-11980) on the changelog page to see if it's resolved in that version:
https://charts.ag-grid.com/changelog/

Thanks again for bringing this up with us.

Kind regards,

David
