### ISSUE TITLE
Funnel chart

### ISSUE THREAD

**Issue by tmskpf** [ag-grid/ag-charts#2321]
Is there any chance you guys adding a funnel chart soon?

**Comment by AG-DavidG** [comment]
Hi @tmskpf 

We are planning to add a funnel chart before the end of this year.

You can track it with this reference:
AG-6875 - [Charts] Add Funnel series type

You can follow the status of feature requests, bugs and releases using our pipeline:
https://ag-grid.com/charts/pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. Once a new AG Charts version is released, look for the item reference above (AG-6875) on the changelog page to see if it's resolved in that version:
https://ag-grid.com/charts/changelog/

Thanks again for bringing this up with us.

Kind regards,
