### ISSUE TITLE
Linear gradient in series fill?

### ISSUE THREAD

**Issue by nicholasalanbrown** [ag-grid/ag-charts#2553]
is there any way to define a linear-gradient for a series fill? I wouldn't have asked her but my post to StackOverflow a couple of months ago got no response.

**Comment by AG-DavidG** [comment]
Hi @nicholasalanbrown 

Thank you for submitting this on Github. 
We do not provide support on StackOverflow at all, and on Github we only take bug reports. I would encourage you to raise any issues via our support portal if you do have an active AG Grid Enterprise licence.

Currently there's no way to implement this behavior with AG Charts. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

You can track it with this reference:
AG-6324 - [Charts] Allow using series fills types including gradient, picture or texture, pattern

You can follow the status of feature requests, bugs and releases using our pipeline:
https://ag-grid.com/charts/pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. Once a new AG Charts version is released, look for the item reference above (AG-6324) on the changelog page to see if it's resolved in that version:
https://ag-grid.com/charts/changelog/

Thanks again for bringing this up with us.

Kind regards,

David
