### ISSUE TITLE
chartRef.download() bar chart with stacked bars, the download is not stacked

### ISSUE THREAD

**Issue by kfaiczak** [ag-grid/ag-charts#2586]
**I'm submitting a ...** (check one with "x")

```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
Latest version 10.2.0
chartRef.current.download()  stops stacking the bars and the bars become 1 pixel wide (since more bars, on x-axis since not stacked)
            chartRef.current.download({
                fileName: filename + " " + title + ".png",
                fileFormat: "image/png",
                width: 1700,
                height: 800,
            })

this chart works in React on the screen (in 10.0.0/10.1.0/10.2.0)
![image](https://github.com/user-attachments/assets/bc164d91-d4d3-4556-ad84-ad708a795c0c)

then when we do the download to png it becomes (10.1.0, 10.2.0)
![image](https://github.com/user-attachments/assets/cf99ef76-9ba9-4dd8-ae0d-69ae58b0fe5b)
bars are no longer stacked
and all become 1 pixel wide 

the  worked fine before result was in 10.0.0
![image](https://github.com/user-attachments/assets/c01d9b86-9842-4e42-b014-c3c5f61b77d2)

ag-charts 10.2.0 (also bug in 10.1.0)
react- 18.3.1
chrome 128.0.6613.121 
macOS 14.5

everything is the same, I just upgraded/downgrade ag-charts (2 pkgs community/react) and get these different results.

**Comment by AG-DavidG** [comment]
Hello @kfaiczak 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-12985 - [Charts] When downloading a stacked bar, the image has grouped bars

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://ag-grid.com/charts/pipeline/

The best way to track this is to sign up for AG Charts new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/15387001154205-How-do-I-Sign-Up-For-AG-Charts-Release-Notifications). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://ag-grid.com/charts/changelog/).

Thanks again for bringing this up with us.

Kind regards,

David
