### ISSUE TITLE
Donut inner title not showing

### ISSUE THREAD

**Issue by danPwiz** [ag-grid/ag-charts#2608]
**I'm submitting a ...** (check one with "x")

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**
No

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are

This is the example from https://www.ag-grid.com/charts/angular/donut-series/#multiple-donuts.
https://codesandbox.io/p/sandbox/7j2cht?file=%2Fmain.ts

**Current behavior**

The title of the inner donut is not displayed. In the code example I can see the title appear and on the first interaction it disappears. (looks like it is based on the size of the chart). In your website the inner donut title isn't displayed at all.

**Expected behavior**

The secondary title will be displayed whenever there is space. In the code example the title shouldn't disappear.

**Please tell us about your environment:**
* macos
* webstom
* npm
* chrome

-   **AG Charts version:** 10.2.0
Also in 10.1.0

-   **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'

-   **Language:** Typescript

**Comment by AG-DavidG** [comment]
Hello @danPwiz 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-13033 - [Charts] Donut title disappears on chart highlight or resize

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://ag-grid.com/charts/pipeline/

The best way to track this is to sign up for AG Charts new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/15387001154205-How-do-I-Sign-Up-For-AG-Charts-Release-Notifications). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://ag-grid.com/charts/changelog/).

Thanks again for bringing this up with us.

Kind regards,

David

**Comment by danPwiz** [comment]
Thank you!
