### ISSUE TITLE
Documentation z-index bug

### ISSUE THREAD

**Issue by imevanc** [ag-grid/ag-charts#2869]
Hey team,

I noticed there is this issue on the docs page. Tested on an iPhone 15 pro max.

![image](https://github.com/user-attachments/assets/b1a68fbd-a8c7-4b29-8d7b-d16ff8c17a2a)

Cheers,
Evan

**Comment by AG-DavidG** [comment]
Hello @imevanc 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-13300 - [Charts][Website] Incorrect Z index for search box on the options API pages

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://ag-grid.com/charts/pipeline/

The best way to track this is to sign up for AG Charts new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/15387001154205-How-do-I-Sign-Up-For-AG-Charts-Release-Notifications). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://ag-grid.com/charts/changelog/).

Thanks again for bringing this up with us.

Kind regards,

David
