### ISSUE TITLE
Clicking on a enabled legend element returns enabled: true

### ISSUE THREAD

**Issue by bykovmikhail72** [ag-grid/ag-charts#2913]
**I'm submitting a ...** (check one with "x")

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```    
    
We are sorry to have to contact you again regarding the issue that has arisen after updating the ag-charts package to the latest version.

**Current behavior**

I use the function in the legend.listeners.legendItemClick. When clicking on the legend element, if I want to turn off the line, the return value is enabled: true. If I want to enable the line, then the value returned is disabled: false.

**Expected behavior**

When I click on the "legend" element to turn the line off, the function returns "enabled: false", and when I want it to be on, it returns "enabled: true". Everything used to work correctly, but now it's not working as expected.    
    
An example from the documentation: In the console, when you click on a enabled legend element, you will see that it returns enabled: true. Link: https://plnkr.co/edit/?open=index.tsx&preview    
    
![image](https://github.com/user-attachments/assets/f3a0c08d-68ac-4dfa-9148-7c74acbdd36c)

**Please tell us about your environment:**

MacOS Sonoma, Visual Studio Code, yarn

-   **AG Charts version:** X.X.X
10.3.1 (latest)

-   **Browser:**

'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'

-   **Language:**     
Typescript 5.5.2., React 18.2.0

**Comment by AG-DavidG** [comment]
Hello @bykovmikhail72  

Thank you for bringing this up with us. 

You're correct - there is a change in the event params in this case.

We will resolve this issue by introducing a new event to handle series visibility changes. We are rebuilding the area for our next major release and the API will change. 

In the meantime, please roll back to the earlier version of AG Charts until we release a new version featuring an event that will allow handling the series visibility changes easier and more consistently.

This is tracked by feature request: AG-13357 - [Charts] Create series visibility change event and remove state from legend click params
 
You can follow the status of feature requests, bugs and releases using our pipeline:
https://ag-grid.com/charts/pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. 

Once a new AG Charts version is released, look for the item reference above (AG-13357) on the changelog page to see if it's resolved in that version:
https://ag-grid.com/charts/changelog/

Thanks again for bringing this up with us.

Kind regards,

David
