### ISSUE TITLE
Duplicate Legend Item IDs When Rendering Multiple AG Charts Instances on the Same Page

### ISSUE THREAD

**Issue by willikercarmo** [ag-grid/ag-charts#3263]
**I'm submitting a ...**  
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**  
The issue occurs when using multiple AG Charts instances on the same page. Each chart generates legend items with duplicate `id` attributes, which violates accessibility standards and causes issues in HTML validation. Here's how to reproduce the issue:

1. Create two charts on the same page using AG Charts.
2. Inspect the DOM to observe the legend items' `id` attributes.
3. Notice that each chart assigns identical `id` values, such as `ag-charts-legend-item-0`, `ag-charts-legend-item-1`, etc., for their respective legend items.

**Current behavior**  
When rendering multiple charts on the same page, the `id` attributes of legend items are duplicated across charts. For example:

Chart 1:
```html
<button id="ag-charts-legend-item-0" ...>Legend Item 1</button>
<button id="ag-charts-legend-item-1" ...>Legend Item 2</button>
```

Chart 2:
```html
<button id="ag-charts-legend-item-0" ...>Legend Item 1</button>
<button id="ag-charts-legend-item-1" ...>Legend Item 2</button>
```

**Expected behavior**  

The expected behavior is that the `id` attributes of legend items can be customized by the user, allowing for unique and meaningful identifiers. For example, users should have the ability to define a prefix or a pattern for the legend item IDs to ensure uniqueness across multiple chart instances. 

This could look like:
```html
<button id="custom-prefix-legend-item-0" ...>Legend Item 1</button>
<button id="custom-prefix-legend-item-1" ...>Legend Item 2</button>
```

This would allow flexibility and ensure accessibility compliance, avoiding duplicate `id` values across charts.

**Please tell us about your environment:**

- **AG Charts version:** 10.2.0
- **Browser:** Chrome 131.0.6778.110 (Official Build) (64-bit)
- **Language:** TypeScript 4.5 / ES6 / React

**Additional notes**  
This issue significantly impacts scenarios where multiple charts are used on the same page. A mechanism to prefix or customize the `id` of legend items per chart instance would resolve the issue.

**Comment by AG-DavidG** [comment]
Hello @willikercarmo 

Thank you for reporting this.

Currently there's no way to implement this behavior with AG Charts. However, we agree this would be a valuable addition to the product and we have added a feature request for this.

You can track it with this reference:
AG-13708 - [Charts] Allow unique ids for DOM elements across multiple chart instances

You can follow the status of feature requests, bugs and releases using our pipeline:
https://ag-grid.com/charts/pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. Once a new AG Charts version is released, look for the item reference above (AG-13078) on the changelog page to see if it's resolved in that version:
https://ag-grid.com/charts/changelog/

Thanks again for bringing this up with us.

Kind regards,

David
