### ISSUE TITLE
ERROR TypeError: def.findHostDirectiveDefs is not a function

### ISSUE THREAD

**Issue by gokberknur** [ag-grid/ag-charts#673]
Hi, 

I wanted to try out new ag-charts, we have a angular 17 applications. I just followed installation instructions and copy pasted line charts code. 

but i am getting this error, is this a bug?

![Screenshot 2023-12-01 at 09 16 28](https://github.com/ag-grid/ag-charts/assets/5589187/bd4c334a-3fa8-4334-87e1-666a63bb1488)

**Comment by AG-DavidG** [comment]
Hello @gokberknur 

Thank you for reporting this behavior - much appreciated!

We're keen to look into this but we need to be able to reproduce the issue you've described.

Please provide the following:

1. A live example (plunker, stackblitz, etc) or link to a repo showing the issue
2. A list of steps to follow to reproduce the issue
3. Descriptions of current behavior and expected behavior

We're looking forward to your response to we can investigate this further.

Thank you!

**Comment by gokberknur** [comment]
Hi, i just made a new angular project and copy pasted my existing code. 

you can access it below. 

https://stackblitz.com/~/github.com/gokberknur/ag-chart-demo

**Comment by robkroll** [comment]
I'm getting the same error, but inside a Storybook story using Angular 16.2.0 and Storybook 7.1.0. I'm not sure what it is for, but there is a check for [findHostDirectiveDefs](https://github.com/angular/angular/blob/d4b423690210872b5c32a322a6090beda30b05a3/packages/core/src/render3/instructions/shared.ts#L1084C52-L1084C52) where it checks for `null`, but for me it is `undefined`.

**Comment by AG-DavidG** [comment]
Hi @gokberknur, @robkroll 

We've identified an issue in our release which affects support for Angular versions of 15+. We are working on a patch which should be available tomorrow.

Thanks

David

**Comment by Evincars** [comment]
Well, in our company project I just decided that we're gonna to use ag-charts except from chartj.js since we're already using ag-grid and business people really love ag-grids. So I hope that this will be fixed asap. We're using Angular 17.

Thank for your work.

**Comment by AG-DavidG** [comment]
Hi All

AG Charts version 9.0.1 has just been released. This is a patch version that supports newer Angular versions up to and including 17.

Thanks

David
