### ISSUE TITLE
Time series axis not fitting to data

### ISSUE THREAD

**Issue by davidchalifoux** [ag-grid/ag-charts#755]
**I'm submitting a ...** (check one with "x")

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

https://plnkr.co/edit/O7AdgXdcNYrjNjTW?open=index.jsx&preview

**Current behavior**

When using a time axis, certain datasets will cause the graph to not fit to the data. Instead, the data points "float" to one side because the axis labels includes dates outside of the range of the data. I've tried manually setting the `min` and `max` values with no success.

**Expected behavior**

The graph should fit to the data, and should not include multiple date labels outside of the data.

**Please tell us about your environment:**

-   **AG Charts version:** 9.0.1

-   **Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

-   **Language:** TypeScript 5.2.2

**Comment by AG-DavidG** [comment]
Hi @davidchalifoux 

This is because the axis is automatically using a 'nice' interval.
If you set `nice: false` then it will only use the time range from the provided data, or the `min` and `max` values.

I have modified your plunker to show this - https://plnkr.co/edit/WJDOwg93BWDxwcu4?open=index.jsx.

Thanks

David
