### ISSUE TITLE
options width and height doesn't work React js

### ISSUE THREAD

**Issue by Luciedeshayes** [ag-grid/ag-charts#791]
In the Options api, the width and heigth properties don't work. I've tested the library on several projects, and I always have the same problem.

**Comment by AG-DavidG** [comment]
Hello @Luciedeshayes !

Thank you for reporting this behavior - much appreciated!

We're keen to look into this but we need to be able to reproduce the issue you've described.

Please provide the following (as per our bug template in Github):
1. A live example (plunker, stackblitz, etc) or link to a repo showing the issue
2. A list of steps to follow to reproduce the issue
3. Descriptions of current behavior and expected behavior

We're looking forward to your response to we can investigate this further.

Thank you!

**Comment by AG-DavidG** [comment]
Hi @Luciedeshayes 

I am closing this issue as we do not have a reproducible scenario to demonstrate the problem you have described.

If you have a reproducible scenario then please let us know and we will be happy to investigate further.

Thanks

David
