### ISSUE TITLE
Not accessible at all

### ISSUE THREAD

**Issue by epimethee** [ag-grid/ag-charts#829]
**I'm submitting a ...** (check one with "x")

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Data is only generated as a \<canvas\>, without any data or semantic tagging. At all. As such, it's preventing people with a wide range of disability from even basic usage or any chart using this. I need to recommend our org avoid AG Charts, as we'd be locking out multiple customers and would be liable to be sued in multiple jurisdictions. 

**Expected behavior**
- Semantic tagging is used.
- Dataset is screeenreader-friendly
- Out-of-the-box colour contrasts are accessible

**Please tell us about your environment:** 

- **Dev environment:** Any

-   **AG Charts version:** 9.0.1

-   **Browser:** Any

-   **Language:** n/a

**Comment by AG-DavidG** [comment]
Hello @epimethee ,

Thank you for bringing this up with us. 

We have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
AG-5929  [Accessibility] Add keyboard navigation and screen reader announcements to charts

You can follow the status of feature requests, bugs and releases using our pipeline:
https://charts.ag-grid.com/pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. Once a new AG Charts version is released, look for the item reference above (AG-5929) on the changelog page to see if it's resolved in that version:
https://charts.ag-grid.com/changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by AG-DavidG** [comment]
Hi @epimethee 

I just wanted to bring to your attention that we have added accessibility to AG Charts with version 9.3 that has just been released.
 
You can read more about this at https://charts.ag-grid.com/react/accessibility/.
 
I hope that this allows you to integrate AG Charts in your offerings. 
  
Thanks

David

**Comment by epimethee** [comment]
Hi @AG-DavidG, that's great news, kudos to your team! I'll update our team with this very positive development.

Thanks for the follow-up.
