### ISSUE TITLE
Not able to change legends fill color

### ISSUE THREAD

**Issue by yashwanth2714** [ag-grid/ag-charts#895]
Hi Team,

We are not able to change legends fill color. 

Please open the below link to see the issue. Subscriptions and Services fill color is black and red but the legends are showing a different color.

https://codesandbox.io/p/sandbox/customised-area-series-forked-rmgvzx?file=%2Fmain.js

![image](https://github.com/ag-grid/ag-charts/assets/36370530/1039cbcb-8f3b-4ea5-9e67-ce088cf1a51b)

AG Charts Version: 9.0.2

**Comment by AG-DavidG** [comment]
Hi @yashwanth2714 

Thank you for bringing this up with us. 

The legend for the area series uses the marker fill colour rather than the area fill colour. However this is not always the desired behaviour.

We have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
AG-10160 - [Charts] Improve area series legend item default colour

You can follow the status of feature requests, bugs and releases using our pipeline:
https://charts.ag-grid.com/pipeline/

It is possible to get the desired colours by adding a marker fill colour and setting the marker size to 0 so that it doesn't show. For each series add `marker: { size: 0, fill: "black", fillOpacity: 0.7 },`. (The default opacity for an area series fill is 0.7 to enable seeing the series at the back.) 

https://codesandbox.io/p/sandbox/customised-area-series-forked-j9kq8y?file=%2Fmain.js%3A29%2C10-29%2C66
![image](https://github.com/ag-grid/ag-charts/assets/121935568/e63c70e0-b7a1-4853-9c2c-07125a761647)

You could also use the `legend.item.showSeriesStroke` option to use the line stroke instead of the fill colour.

https://codesandbox.io/p/sandbox/customised-area-series-forked-4mygs4?file=%2Fmain.js%3A22%2C12
![image](https://github.com/ag-grid/ag-charts/assets/121935568/a752c878-d99b-448a-9ed3-98255a655102)

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. Once a new AG Charts version is released, look for the item reference above (AG-10160) on the changelog page to see if it's resolved in that version:
https://charts.ag-grid.com/changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by yashwanth2714** [comment]
@AG-DavidG Thanks for the solution 😊
