### ISSUE TITLE
Feature Request - Step Line Chart

### ISSUE THREAD

**Issue by Setomiro** [ag-grid/ag-charts#920]
**I'm submitting a ...** (check one with "x")

```
[] bug report => see 'Providing a Reproducible Scenario'
[X] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Hey,
My company is interested in using AG Grid / AG Charts Enterprise. We are already using the trial version to test if our needs will be covered. Right now, we are pretty satisfied with AG Grid and all its features. The AG Charts features are also looking pretty good, but we are missing a line chart variation called Step Line Chart that would fit several of our use cases. Is there any planned support for this variation of the line chart?
Currently, we're using Apexcharts (https://apexcharts.com/vue-chart-demos/line-charts/stepline/) to cover that need, but we are looking to replace it with a general solution for grids and charts.

**Comment by AG-DavidG** [comment]
Hello @SebastianRochert 

Thank you for bringing this up with us. 

If you have a trial key then we recommend that you reach out to our sales team to get setup with support through our Zendesk support system. This will allow us to help with any questions that arise, and provide more assistance than we can through Github.

We have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
AG-10551 - [Charts] Add support for Step series types (line, area) 

You can follow the status of feature requests, bugs and releases using our pipeline:
https://charts.ag-grid.com/pipeline/

Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. Once a new AG Charts version is released, look for the item reference above (AG-10551) on the changelog page to see if it's resolved in that version:
https://charts.ag-grid.com/changelog/

Thanks again for bringing this up with us - we appreciate your time!
