### ISSUE TITLE
Zoom functionality does not work when line chart initializes with few points and receives real time updates

### ISSUE THREAD

**Issue by teokosmo** [ag-grid/ag-charts#946]
**I'm submitting a ...** (check one with "x")

```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Charts team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, our staff will label your issue as managed-by-the-community. This means that AG Grid staff will not be actively looking into it and it will be closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are

-   A description of the detailed steps to reproduce your behaviour in one of our examples in our docs.
-   A Plunker.

If you decide to send us a Plunker, from any example in our website use the Plunker button in there to fork your own code by following the steps below:

-   Select the framework that is appropriate to you from the drop-down
-   Open it in Plunker. (Use the button Plunker in our example)
-   Add your changes so that the behaviour is reproduced
-   Save and Freeze the Plunker (On the top left corner)
-   Send us the link to the Plunker (You can copy the URL from the browser)

https://plnkr.co/edit/n9LbCjKlJTAY30PI

If reporting a bug make sure to state:

-   Current behaviour.
-   Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

Zoom functionality is not enabled when line chart initializes with 3 or less points and receives realtime data updates afterwards

**Expected behavior**

When number of chart points are above a specific threshold (minVisibleItemsX), the user should be able to zoom in the chart using selection or scrolling

**Please tell us about your environment:**

-   **AG Charts version:** 9.0.2

-   **Browser:**

-   **Language:** [all | TypeScript X.X | ES6/7 | ES5]

-  **Plunker:**
https://plnkr.co/edit/n9LbCjKlJTAY30PI

**Comment by AG-DavidG** [comment]
Hello @teokosmo 
 
Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a bug.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-10607 - [Charts] Zoom option of `minVisibleItems` not re-evaluated on data update
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

In the meantime, you can use the zoom functionality in this scenario by setting `minVisibleItemsX` and `minVisibleItemsY` to 1.
 
You can get an update on the status of this item on the product pipeline page:
https://charts.ag-grid.com/pipeline/
 
Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Chartsnew release notifications. Once a new AG Charts version is released, look for the item reference above (AG-10607) on the changelog page to see if it's resolved in that version:
https://charts.ag-grid.com/changelog/
 
Thanks again for bringing this up with us - we appreciate your time!
 
David‍
