### ISSUE TITLE
Time Axis tick interval of every X months gives wrong day in label

### ISSUE THREAD

**Issue by BradWells** [ag-grid/ag-charts#979]
**I'm submitting a ...** (check one with "x")

```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
Plunker below:
https://plnkr.co/edit/tvRb4XcdTzWmNyCA?open=index.jsx&preview
Relevant snippet:
```
            {
                type: 'time',
                position: 'bottom',
                nice: false,
                tick: {
                    interval: time.month.every(5, { snapTo: 'start' }),
                },
                label: {
                    format: '%m %b %Y',
                },
            },
```

**Current behavior**
Dates at the bottom show Jan 1st, Feb 2nd, March 3rd, etc. Adding properties (like `{ snapTo: 'start' }` ) does not change this

**Expected behavior**
Dates at the bottom show Jan 1st, Feb 1st, March 1st by default.
Alternatively, using `{ snapTo: 'start' }` or another similar property gives this behavior.

By December, this results in the tick label having a tick position on the axis around December 1st, but the label says December 12th, which is misleading.

**Comment by AG-DavidG** [comment]
Hi @BradWells 

Thanks for getting in touch and providing an example to illustrate the problem.

In this instance, I believe that the problem lies in the format you are using rather than the `every` function.

The format `%m %b` will show 'month as a decimal number' followed by 'abbreviated month name.' This makes any date in February display as '2 Feb'.

If you use `%d` instead of `%m` to get 'zero-padded day of the month as a decimal number', the labels should display correctly.

For more information about the format codes, please see https://charts.ag-grid.com/javascript/axes-labels/#time-formatting

Thanks again

**Comment by BradWells** [comment]
Ugh, you are absolutely right. That's what I get for copying and pasting.
